---
name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  luacheck:
    name: luacheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint
        uses: lunarmodules/luacheck@v1
