---
name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nvim-versions: [stable, nightly]
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup vim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim-versions }}

      - name: run tests
        run: make test
