---
name: vimdoc

on:
  push:
    branches: [main]

permissions:
  pull-requests: write
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: java-test-util
          dedupsubheadings: false
          version: Neovim >= 0.9.5
          demojify: true

      - name: create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          base: main
          commit-message: 'docs(vimdoc): automatic vimdoc update'
          title: 'docs(vimdoc): automatic vimdoc update'
